pip install requests
pip install Pillow
pip install datetime
pip install psutil
pip install cryptography
pip install discord
pip install httpx
pip install pypiwin32
pip install realtek
pip install wmi
pip install alive-progress
pip install colorama
pip install wniutil
pip install pycryptodome
